---
- hosts: localhost
  vars:
    install_omz: no
    install_spacemacs: no
    install_docker: no
    install_i3: yes
    install_work_tools: no
    install_other_tools: no

  tasks:
    - name: Install omz
      import_role:
        name: omz
      when: install_omz

    - name: Install spacemacs
      import_role:
        name: spacemacs
      when: install_spacemacs

    - name: Install docker
      import_role:
        name: docker
      when: install_docker

    - name: Install other tools
      import_role:
        name: other_tools
      when: install_other_tools

    - name: Install work tools
      import_role:
        name: work_tools
      when: install_work_tools

    - name: Install i3
      import_role:
        name: i3
      when: install_i3
