---
# tasks file for other_tools
- block:
  - name: Install tools via apt
    with_items:
      - vim
      - doublecmd-common
      - curl
    apt:
      name: "{{ item }}"

  - name: Install tools via snap
    with_items:
      - bitwarden
      - flameshot
      - telegram-desktop
    snap:
      name: "{{ item }}"

  - name: Install pgadmin4
    block:
      - name: Add pgadmin4 pgp key
        shell: curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | apt-key add

      - name: Create the repository configuration file
        shell: sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'

      - name: Install pgadmin4
        apt:
          name: pgadmin4

      - name: In link to pgadmin
        command: ln -s /usr/pgadmin4/bin/pgadmin4 /usr/bin

  become: yes
