---
# tasks file for spacemacs
- block:
  - name: Install silversearcher for helm-ag
    with_items:
      - silversearcher-ag
    apt:
      name: "{{ item }}"
  - name: Install emacs
    snap:
      name: emacs
      classic: yes
  become: yes


- name: Install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "~/.emacs.d"

- name: Copy config
  copy:
    dest: "~"
    src: ".spacemacs"
     
