---
# tasks file for i3

- block:
  - name: Add GPG key
    shell: wget -O- https://baltocdn.com/i3-window-manager/signing.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/i3wm-signing.gpg
  
  - name: Install packages for i3
    with_items:
      - apt-transport-https
      - xautolock
      - cbatticon
      - feh
      - i3blocks
    apt:
      name: "{{ item }}"

  - name: Add i3 to source list
    shell: echo "deb https://baltocdn.com/i3-window-manager/i3/i3-autobuild/ all main" | tee /etc/apt/sources.list.d/i3-autobuild.list

  - name: Install i3
    apt:
      name: i3
      update_cache: yes

  become: yes

- name: Copy config
  copy:
    src: "{{ config_file_name }}"
    dest: "{{ config_folder }}"

- name: Copy wallpaper
  copy:
    src: "{{ wallpaper_file_name }}"
    dest: "{{ config_folder }}"

- name: Copy i3blocks config
  copy:
    src: "{{ i3block_config_file_name }}"
    dest: "{{ config_folder }}"

- name: Install font
  command: "wget https://github.com/FortAwesome/Font-Awesome/releases/download/6.0.0/fontawesome-free-6.0.0-desktop.zip -O {{ font_zip_fullpath }}"

- name: Unzip font
  command: "unzip {{ font_zip_fullpath }} -d {{ font_extract_folder }}"

- name: Create fonts folder
  command: "mkdir ~/.fonts"

- name: Copy font to system
  shell: 'mv $(find {{ font_extract_folder }} -name "otfs" -type d)/* ~/.fonts/'
