---
# tasks file for i3

- block:
  - name: Add GPG key
    shell: wget -O- https://baltocdn.com/i3-window-manager/signing.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/i3wm-signing.gpg
  
  - name: Install packages for i3
    with_items:
      - apt-transport-https
      - xautolock
      - cbatticon
    apt:
      name: "{{ item }}"

  - name: Add i3 to source list
    shell: echo "deb https://baltocdn.com/i3-window-manager/i3/i3-autobuild/ all main" | tee /etc/apt/sources.list.d/i3-autobuild.list

  - name: Install i3
    apt:
      name: i3
      update_cache: yes

  become: yes

- name: Copy config
  copy:
    src: config
    dest: "{{ config_folder }}" 

- name: Copy wallpaper
  copy:
    src: wallpaper.jpg
    dest: "{{ config_folder }}"
