---
# tasks file for doomemacs
- block:
    - name: Install emacs
      community.general.homebrew_cask:
        name: emacs
        state: present
      when: ansible_distribution == 'MacOSX'

    - name: Install npm
      community.general.homebrew:
        name: node
        state: present
      when: ansible_distribution == 'MacOSX'

    - name: Install lsps
      with_items:
        - pyright
        - dockerfile-language-server-nodejs
      community.general.npm:
        name: "{{ item }}"
        global: true

    - name: Fetch doom emacs
      git:
        repo: https://github.com/doomemacs/doomemacs
        dest: "{{ emacs_folder }}"
        depth: 1

    - name: Copy configs
      copy:
        src: "doom"
        dest: "{{doom_config_folder }}"

    - name: Generate doom envs
      command: "{{  doom_cmd  }} env"

    - name: Install doom emacs
      command: "{{  doom_cmd  }} install --no-config --install --fonts --hooks"
      debugger: on_failed
