name: Makefile CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ${ls}

    - name: Install ansible
      run: make install-ansible

    - name: Run check
      run: make check-syntax
