name: Makefile CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: echo $HOME

    - run: cat Makefile

    - name: Install ansible
      run: make install-ansible

    - name: Run check
      run: make check-syntax
